#!/usr/bin/env python3
"""
T330 — Bot Swarm Daily Digest
Queries /api/bot/findings/summary, formats a Markdown report,
and optionally sends to Slack via webhook.

Usage:
  python3 scripts/bot-daily-digest.py [--base-url URL] [--slack-webhook URL] [--output FILE]

Env vars:
  BOT_SERVICE_URL   base URL of bot-service (default http://localhost:8089)
  SLACK_WEBHOOK_URL Slack incoming webhook URL (optional)
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from urllib.request import urlopen, Request
from urllib.error import URLError, HTTPError


def fetch_json(url: str, timeout: int = 10) -> dict:
    req = Request(url, headers={"Accept": "application/json"})
    try:
        with urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read())
    except HTTPError as e:
        print(f"[WARN] HTTP {e.code} fetching {url}", file=sys.stderr)
        return {}
    except URLError as e:
        print(f"[WARN] Could not reach {url}: {e.reason}", file=sys.stderr)
        return {}


def build_report(base_url: str) -> str:
    summary   = fetch_json(f"{base_url}/api/bot/findings/summary")
    findings  = fetch_json(f"{base_url}/api/bot/findings?pageSize=5&severity=critical")
    status    = fetch_json(f"{base_url}/api/bot/status")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# 🤖 Bot Swarm Daily Digest — {now}",
        "",
    ]

    # ── Service status ────────────────────────────────────────────────────
    lines.append("## Service Status")
    if status:
        active = status.get("activeBotsCount", "?")
        paused = status.get("pausedBotsCount", "?")
        lines.append(f"- Active bots: **{active}**  Paused: **{paused}**")
        if modes := status.get("activeModes"):
            lines.append(f"- Active modes: {', '.join(modes)}")
    else:
        lines.append("- ⚠️  Status endpoint unavailable")
    lines.append("")

    # ── Findings summary ─────────────────────────────────────────────────
    lines.append("## Findings Summary")
    if summary:
        by_type = summary.get("countsByType", {})
        by_sev  = summary.get("countsBySeverity", {})
        critical = by_sev.get("critical", 0)
        warnings = by_sev.get("warning", 0)
        info     = by_sev.get("info", 0)
        total    = summary.get("totalFindings", 0)

        emoji = "🔴" if critical > 0 else ("🟡" if warnings > 5 else "🟢")
        lines.append(f"- {emoji} Total findings: **{total}** "
                     f"(critical: {critical}, warning: {warnings}, info: {info})")

        if by_type:
            lines.append("\n| Type | Count |")
            lines.append("|------|-------|")
            for t, cnt in sorted(by_type.items(), key=lambda x: -x[1]):
                lines.append(f"| {t} | {cnt} |")

        # Latency stats
        if lat := summary.get("avgApiLatencyByEndpoint"):
            lines.append("\n### API Latency (avg ms)")
            lines.append("| Endpoint | Avg ms |")
            lines.append("|----------|--------|")
            for ep, ms in sorted(lat.items(), key=lambda x: -x[1])[:5]:
                flag = " ⚠️" if ms > 2000 else ""
                lines.append(f"| {ep} | {ms:.0f}{flag} |")

        # 7-day trend
        if trend := summary.get("findingsTrendLast7Days"):
            lines.append("\n### 7-Day Trend")
            lines.append("| Date | Findings |")
            lines.append("|------|----------|")
            for day in trend:
                lines.append(f"| {day.get('date','')} | {day.get('count',0)} |")

        # Conversation health
        if ch := summary.get("conversationHealth"):
            lines.append("\n### Conversation Health")
            lines.append(f"- Active conversations: {ch.get('active', '?')}")
            lines.append(f"- Dead (no reply >48h): {ch.get('dead', '?')}")
            lines.append(f"- Fika suggested: {ch.get('fikaSuggested', '?')}")
    else:
        lines.append("- ⚠️  Summary endpoint unavailable")
    lines.append("")

    # ── Top 5 critical findings ───────────────────────────────────────────
    items = findings.get("items", findings) if isinstance(findings, dict) else findings
    if isinstance(items, list) and items:
        lines.append("## 🔴 Recent Critical Findings")
        for f in items[:5]:
            ts = f.get("createdAt", "")[:10]
            lines.append(f"- **[{f.get('findingType','?')}]** {f.get('title','(no title)')} "
                         f"— {f.get('description','')[:120]} _(bot: {f.get('botPersonaId','?')}, {ts})_")
        lines.append("")

    lines.append("---")
    lines.append(f"_Generated by bot-daily-digest.py — {base_url}_")
    return "\n".join(lines)


def send_slack(webhook_url: str, markdown: str) -> bool:
    # Slack truncates at 4000 chars; send a concise version
    payload = json.dumps({"text": markdown[:3900]}).encode()
    req = Request(webhook_url, data=payload,
                  headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urlopen(req, timeout=10):
            return True
    except Exception as e:
        print(f"[WARN] Slack send failed: {e}", file=sys.stderr)
        return False


def main():
    parser = argparse.ArgumentParser(description="Bot swarm daily digest")
    parser.add_argument("--base-url",      default=os.getenv("BOT_SERVICE_URL", "http://localhost:8089"))
    parser.add_argument("--slack-webhook", default=os.getenv("SLACK_WEBHOOK_URL", ""))
    parser.add_argument("--output",        default="", help="Write report to file (default: stdout)")
    args = parser.parse_args()

    report = build_report(args.base_url)

    if args.output:
        with open(args.output, "w") as fh:
            fh.write(report)
        print(f"Report written to {args.output}")
    else:
        print(report)

    if args.slack_webhook:
        ok = send_slack(args.slack_webhook, report)
        print("Slack: sent" if ok else "Slack: failed", file=sys.stderr)


if __name__ == "__main__":
    main()
